const KON_NIMI = {
    'akesi': {ijo: 'lizard'},
    'ala': {ijo: 'not'},
    'awen': {pali: 'stay'},
    'jan': {ijo: 'person'},
    'jelo': {ijo: 'yellow'},
    'kalama': {ijo: 'sound'},
    'kama': {pali: 'come'},
    'kapesi': {ijo: 'brown'},
    'kasi': {ijo: 'plant'},
    'kepeken': {poki: 'using'},
    'kipisi': {ijo: 'piece'},
    'kiwen': {ijo: 'rock'},
    'kulupu': {ijo: 'group'},
    'lawa': {pali: 'control', ijo: 'control'},
    'linja': {ijo: 'string'},
    'loje': {ijo: 'red'},
    'lon': {poki: 'in', pali: 'exist', ijo: 'real'},
    'lukin': {pali: 'look', e: 'at'},
    'lupa': {ijo: 'hole'},
    'ma': {ijo: 'land'},
    'moku': {pali: 'eat', ijo: 'food'},
    'moli': {ijo: 'dead'},
    'mun': {ijo: 'moon'},
    'mute': {ijo: 'many'},
    'nasa': {ijo: 'strange'},
    'nasin': {ijo: 'way'},
    'ni': {ijo: 'this'},
    'noka': {ijo: 'foot'},
    'ona': {ijo: 'them'},
    'pakala': {ijo: 'broken'},
    'pilin': {pali: 'feel', ijo: 'feeling'},
    'pimeja': {ijo: 'dark'},
    'pona': {ijo: 'good'},
    'sama': {poki: 'like'},
    'sin': {ijo: 'new'},
    'sinpin': {ijo: 'front'},
    'suli': {ijo: 'big'},
    'tawa': {poki: 'towards', ijo: 'movement'},
    'telo': {ijo: 'liquid'},
    'tenpo': {ijo: 'time'},
    'toki': {pali: 'speak', ijo: 'speech'},
    'tomo': {ijo: 'house'},
    'uta': {ijo: 'mouth'},
    'walo': {ijo: 'white'},
    'wan': {ijo: 'one'},
    'weka': {pali: 'leave', ijo: 'away'},
};
