const KON_NIMI = {
    'awen': {pali: 'stay'},
    'jan': {ijo: 'person'},
    'jelo': {ijo: 'yellow'},
    'kapesi': {ijo: 'brown'},
    'kasi': {ijo: 'plant'},
    'kepeken': {poki: 'using'},
    'kulupu': {ijo: 'group'},
    'lawa': {pali: 'head', ijo: 'head'},
    'linja': {ijo: 'string'},
    'loje': {ijo: 'red'},
    'lon': {poki: 'in', pali: 'exist', ijo: 'real'},
    'ma': {ijo: 'land'},
    'moku': {pali: 'eat', ijo: 'food'},
    'mun': {ijo: 'moon'},
    'mute': {ijo: 'many'},
    'nasin': {ijo: 'way'},
    'ni': {ijo: 'this'},
    'ona': {ijo: 'them'},
    'pona': {ijo: 'good'},
    'pilin': {pali: 'feel', ijo: 'feeling'},
    'pimeja': {ijo: 'dark'},
    'tawa': {poki: 'towards', ijo: 'movement'},
    'toki': {pali: 'speak', ijo: 'speech'},
    'tomo': {ijo: 'house'},
    'wan': {ijo: 'one'},
};
